### ISSUE TITLE
pinterest share compatibility issue

### ISSUE THREAD

**Issue by selul** [Codeinwp/optimole-wp#100]
We can check the compatibility with pinterest pin plugins, which might share the lazyload placeholder. 

one example is Sassy Social Share

**Comment by GrigoreMihai** [comment]
** Save images from site option from the official pinterest site works (takes both the placeholders and the original images)

I will add here the tested plugins, tag them with **works** or **doesn't work** and then create compatibilities where needed:

- [ ] Sassy Social Share - **doesn't work**
