### ISSUE TITLE
optimole messed footer logo

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/optimole-wp#101]
https://www.dropbox.com/s/grnl4q2pwmzqejd/Screenshot%202019-05-15%2016.02.50.png?dl=0 cc @selul @preda-bogdan

**Comment by preda-bogdan** [comment]
@ineagu 
cc @selul 

The markup for the image should be `<img src="..." alt="Themeisle Logo" width="160" height="52">`
Now it scales the image to `32px` for height.

The original image is `342x112` and the proportional rescale is `159x52`

**Comment by ineagu** [comment]
@cosmin-serbanescu can look and fix the html then, thanks!

**Comment by cosmin-serbanescu** [comment]
fixed it, big thanks @preda-bogdan
