### ISSUE TITLE
Images not loading

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/optimole-wp#106]
**Describe the bug**
On this demo https://demo.themeisle.com/neve-onboarding-brizy/ built with https://wordpress.org/plugins/brizy/ some of the images are blurred. I think it might be related to Optimole, as the images have the optml_lazyload_img, but I'm not sure. 

**To Reproduce**
1. Go to https://demo.themeisle.com/neve-onboarding-brizy/
2. See blurred images

**Expected behavior**
Images loading properly

@preda-bogdan

**Comment by preda-bogdan** [comment]
**Personal Note** not removing CSS (Intersaction Observer)

**Comment by rodica-andronache** [comment]
if there's any update here, please let me know :) we have quite a few starter sites that we could use when this is fixed. Thanks

**Comment by selul** [comment]
@rodica-andronache this is much harder than it looks as brizy uses some custom method of loading the images which it seems is not compatible with Optimole. 

You or @abaicus can [disable ](https://wordpress.stackexchange.com/questions/3426/how-to-disable-a-network-enabled-plugin-for-just-one-site) Optimole on those sites meanwhile until we find a workaround.

**Comment by abaicus** [comment]
@rodica-andronache @selul Should work fine on demos now. Let me know when this is fixed and you need me to remove the snippet.
