### ISSUE TITLE
possible issues with accents chars

### ISSUE THREAD

**Issue by selul** [Codeinwp/optimole-wp#110]
**Describe the bug**
Example : the image is https://www.oceano.org/wp-content/uploads/2019/06/MOM-façade-nord.png and Optimole generate a link like https://mlekympbvuwm.i.optimole.com/w:auto/h:auto/q:auto/https://www.oceano.org/wp-content/uploads/2019/06/MOM-fau00e7ade-nord.png
 
The replaced url has a the accent char replaced with something else.

**Comment by preda-bogdan** [comment]
This should be fixed here https://github.com/Codeinwp/optimole-wp/commit/86771b3f5d49e1a1f613bcb577e5627f9f083772
