### ISSUE TITLE
Compatibility with Smart Slider & Slider Revolution

### ISSUE THREAD

**Issue by preda-bogdan** [Codeinwp/optimole-wp#128]
Check how both of this work with Optimole make observations about what issues you encounter and let's plan for some changes so we can better support this two.
- [x] Compatibility w. [Smart Slider](https://smartslider3.com/)
- [x] Compatibility w. [Slider Revolution](https://revolution.themepunch.com/)

**Comment by GrigoreMihai** [comment]
there is an issue with smart slider, it adds images as background into a div like this : 'style="background-image: url ("//366b4e08.ngrok.io")' and optimole does not replace that url, the slider also keeps a <img> tag inside that <div> for no reason as far as i can see (removing that <img> tag has no effect on the page) , the link from that <img> tag gets replaced by optimole

**Comment by preda-bogdan** [comment]
Things to have in mind when addressing the issue:

1. Make a test case in phpunit where we send a mock html like the one generated by Smart Slider
2. Make changes on a new branch from `master` eg. `compatibility/smart_slider`
3. Make sure all tests pass and nothing breaks

**Comment by GrigoreMihai** [comment]
i fixed it in last commit to feature/gif_video_tag, i saw your comment after pushing the commit

**Comment by GrigoreMihai** [comment]
i think this is also an issue, optimole plugin replaces links that are added in paragraphs (not compatibility related)

**Comment by GrigoreMihai** [comment]
the modified url's all have w:auto, h:auto no matter what dimensions the slider has, should we make it take the dimensions of the slider (since the image is background to the slider and has same size with it)

**Comment by fxw** [comment]
Hi, exactly the same behaviour for Slider Revolution.

Any date about the release date of this fix ? 

Best regards,
