### ISSUE TITLE
Compatibility with Cache Enabler

### ISSUE THREAD

**Issue by preda-bogdan** [Codeinwp/optimole-wp#136]
Let's check for compatibility with this plugin:

Add to this thread observations

Here is a link to [Cache Enabler](https://wordpress.org/plugins/cache-enabler/)

**Comment by GrigoreMihai** [comment]
i found an issue with the plugin itself without cache enabler, it seems like it removes all html below the  gif it encounters

**Comment by GrigoreMihai** [comment]
an issue without the cache enabler, if the gif replacement option is off and only image replacement is on then a gif resized after it was uploaded in an image block is no longer displayed as a gif and only it's first frame appears in page (it's url is changed properly with optimole format)

**Comment by GrigoreMihai** [comment]
#142
