### ISSUE TITLE
Compatibility top 50 plugins

### ISSUE THREAD

**Issue by preda-bogdan** [Codeinwp/optimole-wp#138]
https://wordpress.org/plugins/browse/popular/

Let's use this list and test top 50 plugins that relate to caching, content creation ( page builders ), or sliders.

We will have a two step process:
1. Make a list with plugins tested and a not for each one ( eg. works | partially works | does not work  )
2. For plugins with issues we can open a new Issue where we detail what was tested, what does not work and possible solutions to the problem.

Tag all new issues following the format `Compatibility plugin_name`

**Comment by GrigoreMihai** [comment]
[ ] Test Plugin - **works**

**Comment by GrigoreMihai** [comment]
**Issues with divi** 
-[ ] Some images do not have lazyload applied to them 
-[ ] Some replaced url's are getting saved into the content of the page
-[ ] It seems like images that dont get lazyload applied to them are also the same that get saved, i will edit this comment after more testing to be sure

**Comment by preda-bogdan** [comment]
@GrigoreMihai can you also test **Cache Enabler** compatibility.

Note: you should be logged out of the admin so use an incognito window to replicate the issue.
