### ISSUE TITLE
Add filter to exclude lazy-load via class

### ISSUE THREAD

**Issue by preda-bogdan** [Codeinwp/optimole-wp#148]
Can we start a new branch from master `feat/lazyload_class_filter`

1. We need to add a new option inside the frontend fo filter via class name
2. Before applying lazy-load check if img tag has one of the classes specified in filters
3. If class is found don't replace img tag with lazyload one.

Let me know if you have questions.

**Comment by nextend** [comment]
Smush use the class named `no-lazyload` to allow exclusion.

In other lazy loading plugins I did see the following attributes used for the exclusion:
`data-no-lazyload="1"`
`data-no-lazy="1"`
`data-hack="data-lazy-src"`

Jetpack's image resizer use a filter to check if that image should be resized or not with the `jetpack_photon_skip_image` filter. Probably it needs more resources than the class/attribute check.

**Comment by selul** [comment]
@nextend thanks for the feedback, that helps. 

We already have filters where people can exclude images from lazyload based on extension, page URL where the image is used and URL of the image.

**Comment by nextend** [comment]
But exclude via class/attribute or filter would allow other plugin and theme developers to disable the lazy loading without any user setting. For example in Smart Slider 3 we have to handle the lazy loading at our side. We can not let other plugins to override it as we need the real image size to be able to properly adjust the slider and layer sizes.

**Comment by selul** [comment]
Makes sense. Do you use a specific class or attribute which we can use to ignore lazyload on those images from the smart slider, which you lazyload? 

Also, the lazyload on your side is mandatory or people can switch off. In case people choose to disable lazyload on a particular slider, it can fallback to our lazyload. 

What do you think?

**Comment by nextend** [comment]
Usually we adapt to lazy loading plugins. So if I would be in your place, I would use the class what Smush use. 

Then I would add that class to the images in Smart Slider 3, when you plugin is present. This is how it happens currently for Smush (and another theme which use the same class):
```PHP
if (function_exists('thb_lazy_images_filter') || defined('WP_SMUSH_VERSION')) {
	$attrs['class'] = 'no-lazyload';
}
```

Well, Smart Slider can not let you handle the lazy loading of the images so it wouldn't work as a fallback. It is about calculations. Slides must be absolute to be able to animate them from of each other. The slider's height is based on the content which are in the slides, so to be able to properly calculate the height, we need to load the images to get their size. Smart Slider Pro in-built lazy loading hooked into this system, but it can only work the background images only. Layer images which reserve space, can not be lazy loaded in slider's context properly.

**Comment by selul** [comment]
@nextend I understand, but based on your feedback, it seems the images from smart slider can't be lazyloaded at all.

Optimole uses a mechanism for lazyloading which might work together with Smart Slider. We use SVG placeholders adapted for each image which uses the same dimensions as the original image. 
Let me give you an example: 
Placeholder: https://iotvnaw69daj.i.optimole.com/w:490/h:256/q:eco/https://mk0codeinwp10tp0961a.kinstacdn.com/wp-content/uploads/2019/02/startablog1.jpg
Image: https://iotvnaw69daj.i.optimole.com/w:490/h:256/q:90/https://mk0codeinwp10tp0961a.kinstacdn.com/wp-content/uploads/2019/02/startablog1.jpg

In this way, you can calculate the proper width/height for the slider and we can do the lazyload. 

What do you think?

**Comment by nextend** [comment]
I didn't know about this mechanism. In that case we should be able to stay compatible with you in most parts. Also I would suggest you to not use my previously suggested `no-lazyload` class. You should use something specific to your plugin, so we would be able to exclude images what really needs to be excluded on our side. For example I would exclude only the slide background images when you plugin activated.

Ps.: I like the way you use SVG to maintain full compatibility with image dimensions ;)

**Comment by selul** [comment]
@nextend yes, right now images lazyloaded thru Optimole use a special attribute for lazyloading, `data-opt-src` which is the original image source. Will it help this on your side?

**Comment by tacodicaprio** [comment]
Is there any plan to extend this to exclude images for optimization as well? 
Image embed code for example, needs to maintain the original image URL.

**Comment by selul** [comment]
hey @tacodicaprio this should be easy to add, I've created a separate issue for this: https://github.com/Codeinwp/optimole-wp/issues/252
