### ISSUE TITLE
Discount code 

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/optimole-wp#152]
@selul sorry if I'm on the wrong place, but I didn't know where else to add this one. After we have changed the pricing model for Optimole, the discount code we have created for AppSump customers is not working anymore.

Even if the code appears as valid, we'll charge the entire amount. 

Ticket example: https://secure.helpscout.net/conversation/964128742/202610?folderId=212385

**Comment by stefan-cotitosu** [comment]
https://secure.helpscout.net/conversation/966780986/202939/

**Comment by mileamadalin** [comment]
Now it should be fixed. I have changed the product package form yearly to monthly.
