### ISSUE TITLE
Test and Compatibility of new features with Builders

### ISSUE THREAD

**Issue by preda-bogdan** [Codeinwp/optimole-wp#156]
**Things we need to achieve:**
We need to test background lazy-load feature with most popular builders.
- [x] Elementor
- [x] Divi
- [x] Beaver
- [x] Thrive

For each builder we need to add classes to watch via `apply_filters( 'optml_lazyload_bg_selectors', [] )` filter in a compatibility file preferably.

Also we can have pages made for `testing.optimole.com` and build some cypress tests for this cases.

**Comment by selul** [comment]
for those, we will need test pages created on testing.optimole.com. We can create one subsite for each builder and set up some proper tests using cypress.
