### ISSUE TITLE
Test and Compatibility of new features with top Sliders

### ISSUE THREAD

**Issue by preda-bogdan** [Codeinwp/optimole-wp#157]
**Things we need to achieve:**
We need to test background lazy-load feature with most popular slider from wp.org.

For each slider we need to add classes to watch via `apply_filters( 'optml_lazyload_bg_selectors', [] )` filter in a compatibility file preferably. Same as with the builders.

Also we can have pages made for `testing.optimole.com` and build some cypress tests for this cases. Here we can use a single page with all the sliders that we want to support.

**Comment by GrigoreMihai** [comment]
for meta-slider if we add the coin slider into the rules for background lazyload, the css rule is not getting removed once the slider is in view

**Comment by GrigoreMihai** [comment]
The fix we have for Master Slider is ok, it is just their plugin that crashes because of the jQuery script being loaded in footer in our testing.optimole.com

**Comment by selul** [comment]
we need to have this working on testing as well, not sure what's happening with the jquery script. We can create a different site for the slider if helps.

**Comment by selul** [comment]
- [ ] the fix for metaslider does not seems to work, the images from the last slider are still loading http://testing.optimole.com/metaslider/ -> https://www.loom.com/share/5985f7af271c412898b56b979a715a38

**Comment by GrigoreMihai** [comment]
they are loading, but not from the background part, they have some </img> tags which we don't lazyload

**Comment by preda-bogdan** [comment]
@GrigoreMihai why we don't lazy load those images, is there a compatibility issue?
Let me know so that we can find a way to progress with this issue and close it.

**Comment by GrigoreMihai** [comment]
yes, it is a compatibility issue the svg get trapped instead of original images, you can close it
