### ISSUE TITLE
webp on safari

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/optimole-wp#161]
@selul Is bit of a weird instance, because I run both shortpixel and optimole, however on safari optimole returned webp : https://www.dropbox.com/s/9naqb93k7peqqo8/Screenshot%202019-10-21%2022.52.36.png?dl=0

Here are more details, the issue seems to be with the offload change since is coming from s3- https://www.dropbox.com/s/j21laxpfqlyizem/Screenshot%202019-10-21%2022.54.16.png?dl=0, https://www.dropbox.com/s/9tdtk86s5xasmhv/Screenshot%202019-10-21%2022.55.14.png?dl=0

**Comment by selul** [comment]
it was an edge case which we manage to fix. 
thanks for reporting
