### ISSUE TITLE
2 requests for same image

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/optimole-wp#164]
**Describe the bug**
We make 2 requests for the logo, while shortpixel makes just 1
**To Reproduce**
1. Install Astra Theme
2. Import the 2nd (Dogs) demo
3. Install Optimole
4. See requests

**Screenshots**
https://www.dropbox.com/s/1yxoi0x0gti1ckh/Screenshot%202019-10-23%2009.56.38.png?dl=0

https://iotvnaw69daj.i.optimole.com/w:auto/h:auto/q:auto/https://scientific-moose.jurassic.ninja/wp-content/uploads/2019/10/site-logo-free-img.svg
https://iotvnaw69daj.i.optimole.com/w:100/h:100/q:auto/https://scientific-moose.jurassic.ninja/wp-content/uploads/2019/10/site-logo-free-img.svg

**Expected behavior**
I would expect a single request

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only Optimole plugin is active.
- [ x] This bug happens with a default WordPress theme active
- [ x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
 WordPress Version: 5.2.4
 Optimole Version: 2.2.1
 PHP versions: 7
</details>

cc @selul

**Comment by selul** [comment]
that's a browser issue when you have disabled cache on.
