### ISSUE TITLE
header image lazy loaded

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/optimole-wp#169]
**Describe the bug**
On this website the logo get lazy-loaded, even if it's in a header tag
**To Reproduce**
1. Go to https://www.mogtahed.com
2. Check the logo image

**Screenshots**
https://www.dropbox.com/s/lmzb5palujwdcu6/Screenshot%202019-10-28%2011.12.28.png?dl=0
**Expected behavior**
Images in the header should not lazy load

cc @selul

**Comment by selul** [comment]
That's the desired behaviour. the avoid lazyloading on images inside header tags, which is not the case here.

**Comment by ineagu** [comment]
I see, not sure if we can improve the matching and look at "header" class or have a rule of thumb, where 1st image on the page is never lazy-loaded
