### ISSUE TITLE
on print, images are missing

### ISSUE THREAD

**Issue by selul** [Codeinwp/optimole-wp#205]
On a page where the lazyload is active when the user try to print it, in the print mode, the placeholders are showing, not the original images.

Would be nice to find a workaround for this.

**Comment by preda-bogdan** [comment]
This can not be achieved for now. Browser support is limited and they react in different ways for the same event.

A temporary workaround is to have a text visible if the page is requested for print that asks the user to use a different link to print the page. The link that the user will be asked to use will have lazy-load disabled.

The text will be visible only on the print preview page and will not be added if lazy-load is disabled.

What do you think about this solution?

to: @selul
cc: @GrigoreMihai

**Comment by selul** [comment]
we can keep this on hold for now.
