### ISSUE TITLE
Test compatibility of css/js feature with major optimizing and caching plugins

### ISSUE THREAD

**Issue by GrigoreMihai** [Codeinwp/optimole-wp#242]
We need to test the new css/js cdn serve feature with the following plugins: 

- [x] Autoptimize - **works**
- [x] W3 Total Cache - **doesn't work** (we do not process the minifyied css/js by their plugin (if their plugin was first on and cached) or all the resources processed by us are cached and are no longer minifyied/concatenated by their plugin if we are first/clear cache after activation of css/js serve) (on short description: either files get served by us and not optimized by w3 or they get optimized by them and not served by us) 
- [x] WP Fastest Cache - **doesn't work** (we do not process the minified css/js files generate by their plugin)
- [x] Hummingbird - **works**
- [x] WP Super Cache - **works**
- [x] Swift Performance Lite - **partially works** (we do not serve the concatenated css/js generated by their plugin, altough the generated files have inside url's processed by us, I guess they do the concatenation later after we processed the files)
- [x] WP Rocket - **works**
- [x] SG Optimizer - **partially works** (everything is ok, except that when the combine css/js options are enabled we do not process the resulting files, altough inside the combined script the images are processed by us)

**Comment by selul** [comment]
@GrigoreMihai for sg optimizer seems like if we start the output buffer after theirs, this will not work, but if we start it before, it will. 
The problem lays into how output handlers works and their order of execution.

We can look into it and see how we can solve it.
