### ISSUE TITLE
investigate compatibility with elementor 3.0

### ISSUE THREAD

**Issue by selul** [Codeinwp/optimole-wp#255]
We need to look into Elementor's new 3.0 version which drops support for some CSS classes which we might use in the bg lazyload option.

We need to check if the lazyloading for backgrounds works just fine with the new version.

**Comment by GrigoreMihai** [comment]
There are 3 clases being removed from elementor : ** .elementor-inner  .elementor-row .elementor-column-wrap **, we are not using them inside the plugin
