### ISSUE TITLE
Blurry Image

### ISSUE THREAD

**Issue by cosmin-serbanescu** [Codeinwp/optimole-wp#263]
**Describe the bug**
This banner from JFT (livedemo pages) looks blurry on retina: https://prnt.sc/tp8hih
Cleared all caches & set it to be excluded from optimizing - doesn't work.

**To Reproduce**
1. Go to justfreethemes.com
2. Click on the live demo btn of any theme.
4. See blurry image on top right

**WordPress Environment**
<details>
 WordPress Version: 5.4.2
 Optimole Version: 2.4.2
 PHP versions: ?
</details>

**Comment by preda-bogdan** [comment]
Is the retina option enabled on JFT, it does not look like that URL is being processed as retina.
Let me know.

**Comment by cosmin-serbanescu** [comment]
yes, it's enabled

**Comment by GrigoreMihai** [comment]
It looks like lazyload is disabled on that page so the retina option will not work, it depends on lazyload being active

**Comment by ineagu** [comment]
I don't think this should be the case right?

**Comment by GrigoreMihai** [comment]
I talked with Cosmin, it was just a typo on the exclusion image name, everything seems ok now.
