### ISSUE TITLE
Feat: Allow users to register image sizes via Optimole

### ISSUE THREAD

**Issue by preda-bogdan** [Codeinwp/optimole-wp#269]
To maybe mitigate issues like this #260 and to allow users more control over the service, we can add a new feature inside the plugin where users can specify dimensions and the plugin will register image sizes for those if they are not already defined.

We can have two inputs for `width` and `height`, and a checkbox for `crop`. Based on the list, we will register using `add_image_size()` new sizes for the user.

In a case like the one mentioned inside #260 a user will be able to register w:278 h:72 with crop enabled, and the carrousel images will be cropped to that dimension instead of scaled to fit.

**Comment by GrigoreMihai** [comment]
Added this here: https://github.com/Codeinwp/optimole-wp/commit/1567e007a73c4fa9bc52144c81332eab648143c2 .
