### ISSUE TITLE
Check compatibility with Elementor

### ISSUE THREAD

**Issue by preda-bogdan** [Codeinwp/optimole-wp#281]
I've seen a recent spike in issues with Elementor and Optimole.
I think they made some changes that might affect compatibility.

We should look into this.

Things to check:
- [x] Compatibility with product gallery, especially zoom images (sometimes they use a different size than auto or maximum size)
- [x] Images sometimes don't get the lazy-load tag
- [x] Elementor post widget

**Comment by GrigoreMihai** [comment]
[ ] I should also check the elementor post widget
