### ISSUE TITLE
Feat: Set plugin options via an environment constant if not defined

### ISSUE THREAD

**Issue by preda-bogdan** [Codeinwp/optimole-wp#293]
We currently have support for agencies to set options via the CLI but we do not cover all current options.
We can add support for all other options as part of the CLI and also have a method to use the options defined in constants via wp-config.php as defaults if the value is not set inside the DB.

This would help developers better integrate into staging to production testing with our plugin as they can set the settings per environment.

**Comment by rodica-andronache** [comment]
https://github.com/Codeinwp/optimole-wp/pull/308 works well from what I've tested
