### ISSUE TITLE
compatibility: Smart WooCommerce Search by Searchanise

### ISSUE THREAD

**Issue by preda-bogdan** [Codeinwp/optimole-wp#294]
This plugin stores the product images on their server and then queries that for results.
When storing we do not process the images and as a result the stored results are of the original URLs.

We should investigate if we can hook into their process and replace the URLs before they save the data.

Also here is a link to the original HS ticket: https://secure.helpscout.net/conversation/1293192971/246717?folderId=2353196

**Comment by rodica-andronache** [comment]
tried to test this, but didn't see any change. As mentioned here https://github.com/Codeinwp/optimole-wp/pull/307 I suppose this depends on the plugin's update, which didn't happen yet from what I've seen
