### ISSUE TITLE
include iframe placeholder if we use iframe on the page

### ISSUE THREAD

**Issue by selul** [Codeinwp/optimole-wp#300]
**Is your feature request related to a problem? Please describe.**
Right now we include an SVG placeholder for the iframe lazyloading which has around 1kB in size. While the approach is fine, I see that we can do some improvements to improve the page weight. 

- [x] Include the iframe lazyload code if the setting is active and if there is a lazyload in the page.
- [x] optimize the SVG code, a simple SVG optimizer can compress the SVG by ~50% and encoding this using rawurlencode vs base64( like we do with generic placeholders) 

**Describe the solution you'd like**
* We can hide the CSS for lazyloading iframe if the setting for that is off and if the method is not used. For an implementation based on the iframe tags on the page, a good start would be to use a static flag inside the lazyload class and turn that on in [this](https://github.com/Codeinwp/optimole-wp/blob/master/inc/lazyload_replacer.php#L281) method. Based on that flag, at the end of the replacement, we can inject the style.

**Comment by rodica-andronache** [comment]
works well from what I've tested 👍
