### ISSUE TITLE
iframe lazy load failing

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/optimole-wp#301]
**Describe the bug**
On this article https://www.codeinwp.com/blog/best-wordpress-hosting/ there is a video at the end embeded using an iframe, the yt css/js is still loading from the start and slows down the page.
**To Reproduce**
1. Go to https://www.codeinwp.com/blog/best-wordpress-hosting/
2. Check waterfall loading
3. Scroll down to the bottom to see the video

**Screenshots**
https://www.dropbox.com/s/zwkvo2buigf2gd1/Screenshot%202020-10-21%20at%2019.48.39.png?dl=0

**Expected behavior**
Have that video lazyloaded and no yt script should be loaded before opening the accordion.

**Isolating the problem (mark completed items with an [x]):**
- [ x] I have deactivated other plugins and confirmed this bug occurs when only Optimole plugin is active.
- [ x] This bug happens with a default WordPress theme active
- [ x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
 WordPress Version: 5.5.1
 Optimole Version: latest
 PHP versions: 7.3
</details>

**Comment by ineagu** [comment]
as a note, this plugin works great: WP YouTube Lyte

**Comment by rodica-andronache** [comment]
I've tested this in https://github.com/Codeinwp/optimole-wp/pull/303 and it works well for me, when the Lazyload for embedded videos and iframes option is enabled
