### ISSUE TITLE
serve lazy script from the user domain

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/optimole-wp#309]
**Is your feature request related to a problem? Please describe.**
It seems that browser caching is not a big deal & since with https loading new connections are more expensive it's more efficient to serve the js script from the same domain where we have the images, that domain also uses pre-connect/prefetch

**Describe the solution you'd like**
It seems that browser caching is not a big deal & with https it's more efficient to serve the js script from the same domain where we have the images, that domain also uses pre-connect/prefetch

**Describe alternatives you've considered**
add pre-connect/pre-fetch to the cloudfront domain

cc @selul

**Comment by selul** [comment]
Just a side note, we already have preconnect and dns-prefetch for CF domainhttps://github.com/Codeinwp/optimole-wp/blob/955f7adf28aeee23fccb6060e29c8c9f22a4be1a/inc/admin.php#L538

**Comment by ineagu** [comment]
Weird I couldn’t see it in the source code of themeisle or codeinwp, would double check

**Comment by ineagu** [comment]
seems that I can't see that across our sites when looking in the source code, I see only the user domain.

**Comment by selul** [comment]
@GrigoreMihai can you shed some light here and see if there are any issues with the preconnect/prefetch?

After this we can look into adding the js lib via the user domain, we can use a cf behavior for this prefix `/js-lib/` which should redirect the request to the bucket.

**Comment by GrigoreMihai** [comment]
Just saw the comment now sorry for late answer, it is just some small typo that causes the preconnect/prefetch to be missing. It comes from the negation on lazyload here: https://github.com/Codeinwp/optimole-wp/blob/master/inc/admin.php#L558
