### ISSUE TITLE
Compatibility: WooFunnels

### ISSUE THREAD

**Issue by preda-bogdan** [Codeinwp/optimole-wp#341]
This plugin conflicts with Optimole when connecting an API key: https://buildwoofunnels.com/wordpress-marketing-automation-autonami/

The steps to reproduce:
1. Have WooFunnels enabled first
2. Then activate Optimole and try to connect via an API key.
3. The Optimole plugin should fail to connect

We should check if we can improve compatibility and not encounter this issue.
Here is the HS ticket for more information.
https://secure.helpscout.net/conversation/1428579357/267091?folderId=2353196

**Comment by tudor-themeisle** [comment]
In my test, Optimole is connecting ( https://prnt.sc/10bz7oa ). 

I have WP 5.7
