### ISSUE TITLE
Clarity around cloud integration

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/optimole-wp#344]
**Is your feature request related to a problem? Please describe.**
Is not clear to me what the feature does. Overall there are lots of small things that don't allow me to trust what's happening because I get no clear information.

**Describe the solution you'd like**
1. Make sure is clear before enabling this feature that the user CAN restore the images: https://prnt.sc/105mamm.
2. I should be able to see how many images are offloaded, how much MB I saved & how much MB I'm using. I have no idea if the check worked or not.
3. Once I did that and I agreed to offload current & new images, what this thing do? Based on the 1st option explanation sounded like the sync is automatic, this option confuses me in thinking that I need to sync: https://prnt.sc/105mamm
4. If I got the media library things look normal, I have no idea if the image is hosted on optimole or my server by using the default view. Ideally, I would have some small icon/notice or whatever.
5. Restore the image to media library is confusing, restore from where? where is the image hosted?
6. When I offload an image I get the notification: "1 image was stored on our server."  our server is too generic
**Describe alternatives you've considered**
Consider maybe a video once the user enable, just explain what it does and how it work and how the user know it worked vs not.

**Additional context**

We should look at the scenario of doing the offloading automatically on plugin activation and how clear would be to users what's going on.

Probably is a good idea to bring more stats about the traffic & the optimization as well, the dashboard screen is not visually confirming me that the plugin is working, the images are optimized in real time and my website it's indeed faster

cc @selul

**Comment by vytisbulkevicius** [comment]
Adding the DOC here for myself to update it once this issue is closed/updated https://docs.optimole.com/article/1323-cloud-library-browsing

**Comment by selul** [comment]
I've changed a bit the texts, https://vertis.d.pr/sTtERc, as the next steps we need to look into adding more stats into the plugin dashboard regarding uploaded images.

**Comment by ineagu** [comment]
For me is still not clear. I see 2 options:

1. Have the sync button and then make it clear than on the switch activation we would offload new images only.

2. Remove the sync option and automatically schedule the sync on switch activation and leave the text as it is.

**Comment by selul** [comment]
Thanks, will try 1 and see how it goes :)

**Comment by ineagu** [comment]
not sure if we can have a notice on sync success at least, like: Congratulations, all your media library have been offloaded to Optimole servers.
