### ISSUE TITLE
Don't optimize images if Image tag contains class not working

### ISSUE THREAD

**Issue by Jorman** [Codeinwp/optimole-wp#349]
Hi, I'm trying to use this option but, or is not working, or I don't understand how to use it.
This's what I do:
I insert one block image then under the `Advanced` block option, I add `Additional CSS class(es)`, let's say `test`
Then under `Optimole`
![immagine](https://user-images.githubusercontent.com/5203988/112385196-9b915f00-8cef-11eb-82fd-beb825712694.png)
Then I clear all caches from `Optimole` and `W3TC`
I reload the page, but the image came from `CDN`
But if I do the same test, but with `Image filename` option, instead `Image class`, after the reload, the image don't came from `CND` but directly from the website

What am I doing wrong?

J

**Comment by selul** [comment]
@Jorman thanks for reporting, we will look into it. At the first sight, the workflow is good and it should work. Do you have the website available as well? Will love to check it out. 

Thanks !

**Comment by Jorman** [comment]
I've, please, for example, see here https://www.goccediveleno.it/segnalibri-gratuiti/
Like you can see I've added some extra css class from Gutenberg blocks, but seems not working, because image class are only under img tag. That's bad because I've to dig every image and extract for example `wp-image-940` or `wp-image-732` and so on, so is not so practical. What is the exact purpose of Image class? Ho can I use it with, in a simplified way with Gutenberg blocks?

J
