### ISSUE TITLE
File download problem

### ISSUE THREAD

**Issue by Jorman** [Codeinwp/optimole-wp#350]
Hi, I'm trying to understand if I can use the `file block` like before, but I don't fine any option inside `Optimole` to avoid this little problem.
Without `Optimole` I can insert a `file block` and connect it to an image, so after a click the browser download the file.
With `Optimole` in action, when I click to download button, the file image is not downloaded but opened.

Is possible to download the original file instead open the `CDN` file? Maybe with `Don't optimize images if option`?

J

**Comment by selul** [comment]
@Jorman right now is not possible such thing but we will have this in mind as a feature request.

**Comment by Jorman** [comment]
Hi, tell me if I wrong, but a very simple and efficient way is to have image class working. Am I right?

**Comment by selul** [comment]
not really, the image class targets the image tags but the file block is using an anchor tag. a workaround is to have some kind of pattern for image name, like -no-replace suffix and you could add that in the exclusion list.

**Comment by Jorman** [comment]
But in this way I always have to "duplicate" the image, the one that is used to be seen and the one for download, I can't use the same. Instead, if I could add some extra css to the download button I can "skip" the image link connected to the download button and optimize the other. But if I understand correctly, the image class exclusion, inside Optimole, don't work with nested css, and is closed only to img tag. So for example I can't simply add extra css like "no-replace" and have the image not replaced, because this's a "nested" css that is the father of img tag that is inside. Sounds strange I know :D maybe is neede a little example with html code

**Comment by selul** [comment]
Yes, you are right. So let's imagine that we have the `test` class to be excluded

**This is working**
```
<img class="test" src="image url"/>
```
**The following examples are not working**
```
<div class="test"> <img  src="image url"/></div>
```
or 
```
<a class="test" href="image url"/>Link</a>
```

I hope this makes sense.

**Comment by Jorman** [comment]
Yes, the explanation make sense.
But I can't understand the real meaning of this function, for a lay people.
Ok I'm not so expert of WordPress, and so maybe you know that, there's any other way to force or add custom img class from Gutenberg or others page editor?
I mean, without touching the code, how can you use this class exclusion?
Do you think, in the future, will be possible to filter nested css class or something like your example?

J
