### ISSUE TITLE
exclude first X number of images from a certain page from lazyload

### ISSUE THREAD

**Issue by selul** [Codeinwp/optimole-wp#355]
A good thing that we could add in the plugin is the ability to exclude first X images from the pages from lazyload, assuming that those images are in the fold. 

The default could be set to 3 and we can offer a setting inside the Lazyload tab to customize this. 

The implementation can assume an internal buffer index which can count the applied lazyload on images and block it on index < desired limit.

**Comment by ineagu** [comment]
a bit unrelated note @selul having a service-connected to webpagetest/gtmetrix that check all the possible settings and pick the fastest config, might be interesting, if not too complex.

I guess we can already test the value of this by offering $199 one-time manual configuration by us for best results and see if anyone cares for auto-config.
