### ISSUE TITLE
Compatibility issue with Jetpack Search plugin

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/optimole-wp#403]
**Is your feature request related to a problem? Please describe.**
Optimole doesn't work with the Jetpack Search plugin so when results are shown on the website (rendered without a page refresh) images are not served by Optimole.
The plan is to make the plugin compatible.

More context to check and can be tested here - https://secure.helpscout.net/conversation/1777228042/308637

**Comment by HardeepAsrani** [comment]
Based on my past experience with Jetpack Search, it's not possible to modify the response as it comes from their servers, not from WordPress.

Maybe if during the sync you send Optimole images, it will save that but only if: 1. They sync featured images that are not from the same website as connected, 2 They don't return images with their own CDN url.
