### ISSUE TITLE
Regenerate Thumbnails & media replace

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/optimole-wp#454]
**Is your feature request related to a problem? Please describe.**

Both functionalities are needed at some point in a website's life and someone using optimole would need to look for another solution.

**Describe the solution you'd like**

If the implementation is straight-forward and simple enough we can bundle it in optimole. If it doesn't create bloat or lose product focus.

**Describe alternatives you've considered**
release those are separate plugins
**Additional context**

**Comment by Nazrinn** [comment]
+1

I wish we could crop stuff too directly from our WordPress dashboard.

**Comment by selul** [comment]
This is available right now.
