### ISSUE TITLE
Deactivating optimization on an image, skip lazy load as well by default.

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/optimole-wp#462]
**Describe the bug**

If we are choosing to not optimize gif images for example, the lazyload is also deactivated for gifs, without any notice. This does not appear as a rule in the lazy load exclusion settings.

**To Reproduce**
1. Exclude gif images for example
2. Test lazy load on the site

**Screenshots**

**Expected behavior**

My preferred default since we do have a dedicated setting for lazyload, would be just to deactivate optimization, but leave lazy load working, can be native, can be without a placeholder, doesn't matter, is important to continue to work, otherwise, this makes the deactivation of optimization feature useless if it affects lazy.

If we do consider that this should work like it is now (not recommended), duplicate the exclusion rule by default in the lazy rules, so the user can at least notice and ever this + notice.

**WordPress Environment**
<details>
 WordPress Version: 6.1
 Optimole Version: 3.5.3
 PHP versions: 7.
</details>

**Comment by selul** [comment]
@ineagu wp core automatically adds native lazyloading, so disabling the optimization should fall back to your expected behavior. 

However, I will look over it to double-check.

**Comment by ineagu** [comment]
is not the case here: https://www.codeinwp.com/blog/starting-a-blog/. The reason can be that native lazy load is not supported by Safari by default.
