### ISSUE TITLE
There is a typo error in the data-opt-optimized-width parameter

### ISSUE THREAD

**Issue by kushh23** [Codeinwp/optimole-wp#468]
### Description
The latest version of the plugin has a typo error in the `data-opt-optimized-width ` parameter.

**Expected behaviour -** `data-opt-optimized-width `

**Current behaviour -** `data-opt-otimized-width `

### Reference
https://vertis.d.pr/i/68wmTd
https://secure.helpscout.net/conversation/2128810934/352736?folderId=2353196

### Technical details
Optimole version - V3.5.5

**Comment by selul** [comment]
@kushh23 is this a regression?

**Comment by kushh23** [comment]
Don't know, couldn't fine this one reported before.
