### ISSUE TITLE
Conflict between Optimole and WebToffee Cookie Consent Plugin with Lazy Load Enabled for Iframes

### ISSUE THREAD

**Issue by kushh23** [Codeinwp/optimole-wp#475]
### Description

There is a conflict between Optimole and WebToffee's cookie consent plugin. This conflict occurs only when Optimole's lazy loading feature for video embeds and iframes is enabled. Upon clicking the "accept cookies" button, a new 404 entry with "/null" appended to the source URL appears. 

Although no visible issues occur on the front end when the user clicks the "accept cookies" button, the 404 is still being logged and can be accessed using the [Redirection](https://wordpress.org/plugins/redirection/) plugin.

### Step-by-step reproduction instructions

1. Install [Redirection ](https://wordpress.org/plugins/redirection/) and [WebToffee's cookie consent plugin.](https://www.webtoffee.com/product/gdpr-cookie-consent/)
2. Enable Optimole's lazy loading feature for video embeds and iframes.
3. Open the site on the incognito tab and Click the "accept cookies" button on the frontend.
4. Observe the 404 error that occurs [Tools > Redirection > 404]

### Screenshots, screen recording, code snippet or Help Scout ticket

In the screenshot, you can see the /null 404 logs: https://vertis.d.pr/i/CHmRm5

https://secure.helpscout.net/conversation/2161117050/358554?folderId=2353196

### Is the issue you are reporting a regression

No

**Comment by GrigoreMihai** [comment]
Added more details on the ticket. To summarize the iframe was already lazyloaded and we were breaking the `data-cli-src` attribute from the other plugin . 

To fix this we will need to add `data-cli-src` to the current list of flags. 

I would go a step further then this issue and add `-src` to the flags list to avoid any other incompatilities .

Currently can be fixed using this if it occurs on other users: https://gist.github.com/GrigoreMihai/da4f830250da34e806baaeb966f8235c .

**Comment by selul** [comment]
> I would go a step further then this issue and add -src to the flags list to avoid any other incompatilities .

Sounds good.
