### ISSUE TITLE
Allow bulk select in Optimole Dashboard

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/optimole-wp#516]
### What problem does this address?

For deleting images, I have to enter each one and click on delete image.

### What is your proposed solution?

Create a toggle that allows the user to make a bulk select to delete images:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/86592992/230665092-24660c7b-516a-4929-ba8c-d8a0bb7a8f0e.png">

**Comment by HardeepAsrani** [comment]
It will eventually be part of https://github.com/Codeinwp/optimole-service/issues/715

**Comment by selul** [comment]
closing this as #850
