### ISSUE TITLE
Fatal error with the Latest update of optimole [v3.6.0]

### ISSUE THREAD

**Issue by kushh23** [Codeinwp/optimole-wp#517]
### Description

The Optimole plugin, version 3.6.0, has been causing a fatal error for several users after they updated their plugin. This issue has been reported continuously by multiple users, indicating a widespread problem.

Upon updating to Optimole plugin version 3.6.0, users have experienced a fatal error that has caused their websites to crash. This error has been persistent across different WordPress themes and hosting environments, indicating that it is not limited to a specific setup.

Many users reported that they are unable to access "Posts" from within the WordPress admin panel.

A special tag `latest-update-issue` has been added to the mailbox to differentiate tickets related to this specific issue. Rolling back the plugin to v3.5.7 fixes the issue for now.

### Step-by-step reproduction instructions

I was not able to replicate it on a clean instance.

### Screenshots, screen recording, code snippet or Help Scout ticket

The error message displayed is:

> Warning: require(/home/wwwawlho/imjoshuasdad.nz/wp-content/plugins/optimole-wp/vendor/codeinwp/themeisle-sdk/assets/js/build/index.asset.php): failed to open stream: No such file or directory in /home/wwwawlho/imjoshuasdad.nz/wp-content/plugins/optimole-wp/vendor/codeinwp/themeisle-sdk/src/Modules/Promotions.php on line 517
> 
> Warning: require(/home/wwwawlho/imjoshuasdad.nz/wp-content/plugins/optimole-wp/vendor/codeinwp/themeisle-sdk/assets/js/build/index.asset.php): failed to open stream: No such file or directory in /home/wwwawlho/imjoshuasdad.nz/wp-content/plugins/optimole-wp/vendor/codeinwp/themeisle-sdk/src/Modules/Promotions.php on line 517
> 
> Fatal error: require(): Failed opening required '/home/wwwawlho/imjoshuasdad.nz/wp-content/plugins/optimole-wp/vendor/codeinwp/themeisle-sdk/assets/js/build/index.asset.php' (include_path='.:/opt/cpanel/ea-php73/root/usr/share/pear') in /home/wwwawlho/imjoshuasdad.nz/wp-content/plugins/optimole-wp/vendor/codeinwp/themeisle-sdk/src/Modules/Promotions.php on line 517

HS - this is one reference ticket - https://secure.helpscout.net/conversation/2207665147/365030?folderId=2353196
All tickets reporting about this contains - `latest-update-issue`  tag.

### Is the issue you are reporting a regression

No

**Comment by HardeepAsrani** [comment]
@kushh23 This should be fixed now, can you confirm once users reply?

**Comment by kushh23** [comment]
@HardeepAsrani Sure, let me reply to them about the fix and I will keep you posted with an update.

**Comment by kushh23** [comment]
@HardeepAsrani Users have confirmed that the latest update resolved the issue for them. We can close the issue now ✌️
