### ISSUE TITLE
Some trials on Optimole's WP Media Integration

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/optimole-wp#522]
I spent some time, as per my Ninety rock, exploring a few options and what can be improved/added to Optimole WP media integration.

The initial idea was to use WordPress 6.2 Media Integration in Inserter like here:

<img width="683" alt="Screenshot 2023-04-16 at 6 22 59 AM" src="https://user-images.githubusercontent.com/2649903/232262399-32e107c2-d108-4852-99e2-7ae66e5eeda8.png">

After trying a few things and digging into the code, there doesn't seem to be any option available in Block Editor to add custom library to the Inserter at this point.

Another option I explored was how we can integrate Folders into the Media Libray modal, here's an image from one of the plugins.

<img width="1643" alt="Screenshot 2023-04-16 at 6 31 39 AM" src="https://user-images.githubusercontent.com/2649903/232262424-0ce5539f-1e2e-44b6-8c17-670db1448dc1.png">

The UI here can just be what we do in Optimole Dashboard with Folders:

<img width="1400" alt="Screenshot 2023-04-16 at 7 42 59 AM" src="https://user-images.githubusercontent.com/2649903/232262494-070776ef-9a16-4c8e-bedc-2972de1fc9d9.png">

And lastly I tried the WP Library plugin that we got but it seems to focused on different thing and might be hard to transition to Optimole but something inspired by it and few other Media organization options:

If you have enabled automatic upload media library to Optimole, we can have an option to replace the WP Media library integration to see Folders management option of Optimole:

![screenshot-1](https://user-images.githubusercontent.com/2649903/232262527-cd5bc9a5-3873-485e-ba05-0177acaeabdb.png)

**Comment by selul** [comment]
thanks for the research, will close this as there is no immediate action outlined here.
