### ISSUE TITLE
Check the build comments workflow

### ISSUE THREAD

**Issue by GrigoreMihai** [Codeinwp/optimole-wp#524]
Currently the workflow is posting new comments on the pr. 

The desired behaviour is to update the first comment with the new build.

eg: https://github.com/Codeinwp/optimole-wp/pull/521 .

**Comment by selul** [comment]
@GrigoreMihai here my gues is that is happening due to the wrong author check here https://github.com/Codeinwp/optimole-wp/blob/master/.github/workflows/build-dev-artifacts.yml#L87

**Comment by GrigoreMihai** [comment]
> @GrigoreMihai here my gues is that is happening due to the wrong author check here https://github.com/Codeinwp/optimole-wp/blob/master/.github/workflows/build-dev-artifacts.yml#L87, it should be pirate-bot not the one used there.

Thank you for the suggestion, you are right this was the problem, tested here and it fixes the issue: https://github.com/Codeinwp/optimole-wp/pull/525 .
