### ISSUE TITLE
More clarity for Enable cloud library browsing option

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/optimole-wp#537]
This suggestion comes from Kanta, our video creator. During his experience with Optimole's cloud library browsing, he had a hard time understanding the cloud library feature.

He suggested that the explanation from the plugin can be rephrased to be more clear:
Give this site access to all images from your account.
<img width="1154" alt="image" src="https://github.com/Codeinwp/optimole-wp/assets/86592992/cf64e6a2-5f10-42b8-af03-5023b5750d7a">

**Comment by vytisbulkevicius** [comment]
@abaicus,

I think we can make this small change in the next version too if you agree.
It could be:
"_Grant permission for this site to access all images stored in your Optimole account._"
