### ISSUE TITLE
Update plugin title

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/optimole-wp#557]
### What problem does this address?

@abaicus Right now we're missing avif/webp from the title, which is among the biggest feature people are looking for, here is how I suggest updating the title : 

from: Image optimization & Lazy Load by Optimole 

to: Image Optimization by Optimole - Lazy Load, CDN, Convert to WebP & AVIF

@Codeinwp/marketing let me know if you have any thoughts.

**Comment by atikurTonmoy** [comment]
Lazy Load, in my opinion, is a nice keyword to target towards. Thus, the title might remain as:
Image Optimization & Lazy Load by Optimole - Convert to WebP & AVIF

Additionally, I believe we should update our tags and short description.

- First five Tags: lazy load, image optimization, convert webp, image, resize
- Other Tags: image optimizer, compress images, optimize images, optimization, free cdn

- Short description:
Auto compress, optimize & resize images. Convert to WebP & AVIF, serve via CDN. Our image optimizer includes lazy load for speed⚡

CC @ineagu

**Comment by ineagu** [comment]
@abaicus I would ping you here when we have a final version, I think I tagged you too early :).

@atikur, let's keep this focused on the title only, if you have ideas for the other fields, we can create a different issue & discuss. For description & title, CTA influence should also be considered, not only keywords.

I think we may be right that we can experiment with changes gradually, lazy load is a useful keyword as well. What if we do now : 

from : Image optimization & Lazy Load by Optimole

to: Image Optimization by Optimole - Lazy Load, CDN, Convert to AVIF & WebP

**Comment by atikurTonmoy** [comment]
Thank you for pointing that out @ineagu. Btw here my username is @atikurTonmoy :D. 

I appreciate your consideration of CTA influence and keywords in the title. I agree with your suggested modifications but have one small tweak. Given that '[Convert to WebP](https://prnt.sc/DpfBP4YmMJ6r)' has a higher search volume than '[Convert to AVIF](https://prnt.sc/pnEMngS8r_nx)', I propose we switch their places. So, the title would read: 'Image Optimization by Optimole - Lazy Load, CDN, Convert to WebP & AVIF'.

This way, we're still capturing the most searched terms while incorporating all the relevant features. What do you think?

**Comment by ineagu** [comment]
@atikurTonmoy Okay, we can go with that. The order is not super important. My logic on the volume was that what we have now is a lagging indicator, the avif is new but superior and it should replace webp, here are the YoY trends for the individual keyword: https://vertis.d.pr/i/JSPVR7. webp is still more popular, but decreased -by 19%, avif increased 91% ( this is April)


@abaicus we can update the title to Image Optimization by Optimole - Lazy Load, CDN, Convert to WebP & AVIF. If you have any concerns that this would impact the product's success, let me know.

@vytisbulkevicius I think a good pattern that we can introduce for marketing & product ideas is to make sure that a way to measure the success is mentioned within the instructions. 

E.g here, besides the ranking monitoring, @atikurTonmoy would monitor the Metabase for the nr of new users & new connected sites to make sure there is improvement there.

**Comment by abaicus** [comment]
@ineagu I've updated the plugin name. 👍🏻
