### ISSUE TITLE
Ability to Exclude Retina Format for Specific Images

### ISSUE THREAD

**Issue by kushh23** [Codeinwp/optimole-wp#564]
### Description

A customer has requested the implementation of a feature that allows for excluding certain images from being served in retina format. Currently, they have a website with lazyloaded images, and these images are automatically served in retina format, leading to larger image sizes and slower site performance.

While the user can currently exclude the images from lazyloading, this also prevents them from being served in retina format. However, the customer wishes to retain lazyloading functionality for these images while excluding the retina format specifically.

HS - https://secure.helpscout.net/conversation/2269282521/372610

### What is your proposed solution?

Just like we have the option to exclude the images from lazyload/optimization, we can enable users to selectively exclude certain images from being served in retina format while still benefiting from lazy loading for those images. 

Thank you for considering this feature request.

**Comment by kushh23** [comment]
p.s - Feel free to close this if it is not achievable or if it doesn't makes sense to exclude the images from retina format. I just wanted to forward the request that came from the customer to know the different views on this.

**Comment by selul** [comment]
In this instance, I was seeking additional clarity from the client. I believe that our upcoming feature #506 will address the issue they're experiencing.

However, I find this proposal particularly useful and recommend proceeding as follows:

- Implement a mechanism within the js library to bypass the application of retina when the image has a certain class.
- Make this specific class configurable within the library parameters, with a default value of empty.
- Incorporate a PHP filter that enables users to set this using optml_dpr_skip_class, which will default to empty.
- While there is no immediate need for this, I would suggest considering it a lower priority.

Of course, if there are better alternatives we can consider them too.
