### ISSUE TITLE
A potential issue with images not offloading properly

### ISSUE THREAD

**Issue by kushh23** [Codeinwp/optimole-wp#594]
### Description

Hey there, while checking this [ticket](https://secure.helpscout.net/conversation/2231127230/368200?folderId=2353196), I noticed an issue related to image offloading. Occasionally, when attempting to offload big sized images, the file name is modified and appended with the keyword "scaled". These images appear as offloaded to Optimole, but when we navigate to the respective folder, we can see that the scaled image file is still present. Normally, when an original file is removed or deleted, the WordPress-generated sizes of that image are also removed from the site. However, in this particular case, that does not happen.

I suspect that this behavior might be caused by optimole, as it deviates from the expected behavior.

For more context, check the screencast I provide below.

P.s- It doesn't happen with all types of images and I noticed that it is not offloading the scaled version mostly but sometimes it doesnt offload the original image as well (I have example of both)

### Step-by-step reproduction instructions

1. Install optimole and try to offload these images - [1](https://vertis.d.pr/i/4v7NdE), [2](https://vertis.d.pr/i/9iku5H), [3](https://vertis.d.pr/i/5NlV5w).
2. You will see it gets appended by scaled and this scaled version appears on the site taking the storage.

### Screenshots, screen recording, code snippet or Help Scout ticket

https://vertis.d.pr/v/OjfMus
https://secure.helpscout.net/conversation/2231127230/368200

### Environment info

https://pastebin.com/Up5qx7aY

### Is the issue you are reporting a regression

No

**Comment by kushh23** [comment]
for the images I shared, the sizes are bigger - https://vertis.d.pr/i/eH4WHE, https://vertis.d.pr/i/UGGfEM, https://vertis.d.pr/i/VoUxVa

**Comment by abaicus** [comment]
@kushh23 the scale gets appended when uploading large image sizes. Similar to what I mentioned in [this comment](https://github.com/Codeinwp/optimole-service/issues/934#issuecomment-1621388269), WordPress core has a "big image threshold". When you upload something that exceeds that, the attachment name is appended with `-scaled` and it gets scaled down. 

This is default WordPress core behaviour and has nothing to do with Optimole: 
![image](https://github.com/Codeinwp/optimole-wp/assets/15010186/20dde458-6742-4d84-8d8c-98905a08fceb)

**Comment by abaicus** [comment]
The screenshot above is from an instance on TasteWP where I uploaded one of the images you linked. It doesn't have Optimole installed 😬

**Comment by kushh23** [comment]
yes, I agree this scaled being added is not related to Optimole, my question was more that the images of this version are not offloaded properly.

**Comment by kushh23** [comment]
see this - https://mlacbagd4zkv.i.optimole.com/w:auto/h:auto/q:mauto/process:12/id:6d6caec61324630a046901dbef79d5c8/https://active-ant-macu.vertisite.cloud/landscape_art_road_127350_5120x2880.jpg

https://active-ant-macu.vertisite.cloud/wp-content/uploads/2023/07/landscape_art_road_127350_5120x2880.jpg

**Comment by kushh23** [comment]
more on this: If we follow the instructions shared in [this comment](https://github.com/Codeinwp/optimole-service/issues/934#issuecomment-1621388269) by Andrei, the issue gets solved for newly uploaded images.

I have tested it with this gist - https://gist.github.com/kushh23/65e1d0efbcd688c5d43d8623154bce71
