### ISSUE TITLE
Iframes resizing?

### ISSUE THREAD

**Issue by kushh23** [Codeinwp/optimole-wp#608]
### What problem does this address?

A user recently raised a question about whether such a feature is available or not. Currently, we have lazy loading enabled for iframes, which helps improve the page loading speed and overall performance. However, resizing the iframes dynamically could further enhance the user experience.

I am curious to see if implementing it is possible or not as we dont have any URL to change the width and height parameter. But I have searched and found that there are some other wp plugins made for this 👀

Let me know your thoughts on this.

https://secure.helpscout.net/conversation/2306804227/378326

### What is your proposed solution?

Enabling Iframes to be resized dynamically

### Will this feature require documentation? (Optional)

I dont know.

**Comment by abaicus** [comment]
@harshitarora-in This is a low priority for us, and I don't think it makes sense to implement it. I don't clearly understand what the problem he is referring to is exactly, but I don't think optimole is the tool to fix it. 

Also, in the screenshots he's sharing, the browser window is just zoomed to 200%, not resized to a mobile screen.

**Comment by selul** [comment]
@kushh23 I agree with this, adding Iframe resizing adds no benefit for the performance of the site, so it adds no value to the feature.

**Comment by kushh23** [comment]
Yes, I agree with this too. Thank you for looking into this and sharing your views 🙌
