### ISSUE TITLE
Scrollbar Not Working on Cloud Library Site Selection

### ISSUE THREAD

**Issue by kushh23** [Codeinwp/optimole-wp#612]
### Description

The scrollbar on the site selection section of the cloud library is not functioning as expected. Users are unable to scroll through the list of sites when trying to select a site from the available options.

### Step-by-step reproduction instructions

1. Navigate to **Optimole > Settings > Cloud Integration**.
2. Attempt to scroll through the list of available sites using the scrollbar.

### Screenshots, screen recording, code snippet or Help Scout ticket

https://www.loom.com/share/ab5ee52f86c343d99a555fe179576561?sid=1bffaf32-f9de-48be-a6e6-decf52b88e5f
https://secure.helpscout.net/conversation/2313850491/379338

### Is the issue you are reporting a regression

No

**Comment by abaicus** [comment]
@kushh23 This is the form token field from WordPress core. It seems that it scrolls just fine, even if the buttons don't work on the scrollbar. I don't think we can do much about it, as the same thing happens to the component itself:

https://wordpress.github.io/gutenberg/?path=/story/components-formtokenfield--default&args=__experimentalAutoSelectFirstMatch:true;__experimentalExpandOnFocus:true;isBorderless:false;__experimentalShowHowTo:true
