### ISSUE TITLE
Images imported from DAM should use plugin settings

### ISSUE THREAD

**Issue by abaicus** [Codeinwp/optimole-wp#616]
Right now, we don't use the proper URLs to set all the flags for images imported from the DAM. 

We should add the flags that reflect the plugin settings to those images as well, similarly to how we do it for the gravity parameter.

This includes, but not limited to: `f:best`, `ig:avif`, `sm:0`, etc.

**Comment by rodica-andronache** [comment]
@abaicus everything's working well here 🚀
