### ISSUE TITLE
Allow to enter manually numbers in the with/height sliders in the cloud library

### ISSUE THREAD

**Issue by Nazrinn** [Codeinwp/optimole-wp#620]
### What problem does this address?

I find it pretty frustrating to use the slider in the cloud image browser and try to obtain an exact width or height size for an image.

### What is your proposed solution?

Allow a number input field to adjust the size slider values.

### Will this feature require documentation? (Optional)

No.

___
### [Figma](https://www.figma.com/file/m1h6vGH5aVujebg4lLdaOH/Optimole-Plugin-UI?type=design&node-id=3656-27310&mode=design&t=R36StZrNoPs7PekE-11)

**Comment by selul** [comment]
Good point, we will review this. Thanks for sharing this with us.

**Comment by mghenciu** [comment]
Thank you for your feedback, @Nazrinn
I think this is a very good idea.

What we can do is either find a middle ground, having **both the Sliders and the Manual input:**
<img width="986" alt="image" src="https://github.com/Codeinwp/optimole-wp/assets/52494172/97212373-a6ad-45c4-a6ab-f209484a2dd9">

___
or remove entirely the Sliders, and use **only Manual inputs for the Size**:

<img width="964" alt="image" src="https://github.com/Codeinwp/optimole-wp/assets/52494172/a2affb01-1ee4-4bb6-b9e4-ea08de96f4b7">



Let me know your thoughts, and which one you think will work the best.
Personally, I think Sliders are not needed for this case - so we can definitely use only the Manul Input fields.

cc. @JohnPixle

**Comment by mghenciu** [comment]
Thank you for the prompt answer and code snippet, Nazrinn.
The suggestion with keeping the same aspect ratio make sense. Here's a potential direction:
<img width="1153" alt="image" src="https://github.com/Codeinwp/optimole-wp/assets/52494172/a72efd92-b7c0-4b5a-9da0-e4a8f7612fbb">


**We'll explore more this improvements when the implementation phase will start.**

**Comment by selul** [comment]
Hey there, 

Great insights; thank you all for your contributions. I wanted to bring one aspect into the discussion, the fact that we have the Resize dropdown, which should accommodate the preserve ratio behavior. 

I.e when Fit is selected, the system resizes the image while keeping the aspect ratio to fit a given size. 

I think what we can do more is allow those input numbers, but adjust the sliders when the values are changed based on the Resize behavior. 

What do you think?

**Comment by mghenciu** [comment]
> I think what we can do more is allow those input numbers, but adjust the sliders when the values are changed based on the Resize behavior.

This sounds good.

I assumed that the Resize option does what you mentioned, Marius. 
But I am not 100% sure it works as expected. For the image below I changed the image size to Fill, without seeing any changes even in the link: https://mlymuwv4451b.i.optimole.com/cb:mP6lFbtR.lcvOhl1G/rs:fill:385:174/g:noea/id:fcea35e0d74acd407e3a80bf70f537af/https://molehq.vertisite.cloud/porsche_918_spyder_prototype_1920x1080_28267.jpg
<img width="1698" alt="Screenshot 2023-08-07 at 17 20 25" src="https://github.com/Codeinwp/optimole-wp/assets/52494172/790ed0a1-307e-4e5e-9a34-0e335a8a59a3">

___

Also, I am thinking if with this resize we understand we same thing as other products do. For example in Cloudinary, Imagkit and others - the idea with this is to Crop and image (of course having the option to adjust the image to be Fill or Fit).

<img width="1724" alt="Screenshot 2023-08-07 at 17 21 29" src="https://github.com/Codeinwp/optimole-wp/assets/52494172/32c8dd17-f79b-4323-934a-134f739665be">


But in our case this is more like a changing the image size, not actually cropping it.

**Comment by Nazrinn** [comment]
Also just saying that I agree with @mghenciu demo's with the checkbox saying "Maintain Aspect Ratio". This is similar to how you can resize images in Photoshop so I can imagine this would feel familiar for at least some users.

I'm not sure if fit/fill are very clear to most users. As I understand one is for maintaining the aspect ratio (resizing) and the other doesn't (cropping; from the sides toward the middle)?

**Comment by selul** [comment]
> As I understand one is for maintaining the aspect ratio (resizing) and the other doesn't (cropping; from the sides toward the middle)?

Indeed. 

> This is similar to how you can resize images in Photoshop so I can imagine this would feel familiar for at least some users.

I agree, however, I think this will duplicate the functionality of the resize dropdown; maybe replacing the texts in the resize dropdown to make them easier to understand will solve the problem. 

> But I am not 100% sure it works as expected. For the image below I changed the image size to Fill, without seeing any changes even in the link:

Yes, based on your description it might be a bug here.

**Comment by mghenciu** [comment]
I suggest for now we stick to adding the Input fields, where user can add the numbers.
And also since we have [this issue](https://github.com/Codeinwp/optimole-service/issues/1007) in the upcoming release, we can **add a helper text** - which should help users understand what each of those option does.

![Screenshot 2023-08-08 at 16 50 21](https://github.com/Codeinwp/optimole-wp/assets/52494172/666fd5e8-5bc3-4db9-bc70-05dc9e747985)


Later we can review this more, also think about integrating a **Image Crop** feature.

___
I'll create an issue for the mentioned bug, Marius.

**Comment by mghenciu** [comment]
I'll mark this as Ready for Dev.
Ping me if other design changes are required.
