### ISSUE TITLE
Allow the generic lazyload placeholder to have a specific color instead of being transparent

### ISSUE THREAD

**Issue by Nazrinn** [Codeinwp/optimole-wp#624]
### What problem does this address?

I find it helpful when scrolling down a website to see exactly where images will appear. With a transparent placeholder, you can only assume where an image will appear due to layout spacing, but sometimes you expect an image where there is actually none and you end up waiting for nothing or thinking the website is broken because no image loaded.

### What is your proposed solution?

Add the possibility to pick a color and alpha channel value for the generic lazyload placeholder, similar to how LiteSpeed Cache does it.

![image](https://github.com/Codeinwp/optimole-wp/assets/36900693/0a2659ad-c1d0-4a45-be9f-339c570d181b)

This might mean to add an image to the page, depending of the implementation.

### Will this feature require documentation? (Optional)

Yes, it requires documentation.

___
### [Figma](https://www.figma.com/file/m1h6vGH5aVujebg4lLdaOH/Optimole-Plugin-UI?type=design&node-id=3766-29218&mode=design&t=cwAqtKLCwSLpCZz1-11)

**Comment by abaicus** [comment]
@Codeinwp/design-team, we need some control for the color of the image lazyload placeholder in the Optimole settings.

**Comment by mghenciu** [comment]
> https://github.com/orgs/Codeinwp/teams/design-team, we need some control for the color of the image lazyload placeholder in the Optimole settings.

I tried something in Figma. 

From what I understood, this feature is related to **Enable generic lazyload placeholder**, but let me know if it should live inside another Panel.

<img width="1767" alt="image" src="https://github.com/Codeinwp/optimole-wp/assets/52494172/b7e261ac-bdcd-469b-92d0-e5ee69bd6a4b">

**Comment by abaicus** [comment]
@mghenciu Yes, that is right. It's tied to the generic placeholder. I think we should display it conditionally based on the status of the generic placeholder setting 👍🏻

**Comment by mghenciu** [comment]
Thank you Andrei for the quick response.
So I assume that option is ok to live inside the Enable generic lazyload placeholder panel, and **visible only when enabled.**

I'll just wait to see what @JohnPixle, thinks about it UI.

Also, I adjusted the text a bit, so it mentions the color and for a better writing. Ideally it should stay on 2 lines; if not - I'll try to make it a bit shorter.
<img width="1789" alt="image" src="https://github.com/Codeinwp/optimole-wp/assets/52494172/33ad7529-3c22-42d5-9522-66c75db66e7b">

**Comment by Nazrinn** [comment]
@mghenciu please keep in mind that you could use a link to Optimole's documentation to keep the text shorter like I proposed in #621!

**Comment by abaicus** [comment]
@mghenciu @JohnPixle, I agree that we should add a doc link instead of expanding the text. Here's how it will look:

![image](https://github.com/Codeinwp/optimole-wp/assets/15010186/73307d37-c729-433c-82e6-097d63bd4da3)

![image](https://github.com/Codeinwp/optimole-wp/assets/15010186/13501ec0-7f2a-4e47-90fa-438d881bd3f6)

**Comment by mghenciu** [comment]
Looks good!
I think we can improve the text later, depending also on how we change the details in the docs.

Or we can go for something like this: _Enabling this will replace the low-quality image with a generic transparent placeholder, reducing the number of requests and page weight. However, this might affect the user experience in some cases. More details here_

basically explaining the feature.
