### ISSUE TITLE
Research offloading without actually replacing the image URLs in the database

### ISSUE THREAD

**Issue by abaicus** [Codeinwp/optimole-wp#664]
## Summary: 

Right now, we are replacing links in the database. This is a cumbersome and unreliable process, especially on large sites with a lot of content. If things go wrong with the offload/rollback, the users might encounter issues with images that are not displaying anymore.

## Proposed solution:

We should research if there's a possibility to do the offload without replacing the links. 

A potential problem could be when images are used in various editors (i.e. Elementor / WordPress Editor / etc.), as these images are not on the website anymore, so the editor should show the remote link. Still, upon saving, we should save the initial link into the database to replace it with a link pointing to the remote image, leveraging the same process we have when replacing links.

## Requirements:

- This enhancement should be enabled for new users of the feature (users who do not have the offload enabled);
- We should set a flag based on the offload status when the version having this enhancement is first run;
- If the offload was enabled, we would keep the legacy process for everything for these users;
- For new users, the process should do the following:
  - Offload all their images to the cloud like we already do;
  - These images should be appropriately flagged with a post meta - Right now, we use `wp_attachment_metadata`, which adds additional complexity;
  - Ensure that the proper URLs are replaced in the content, leveraging the replacer functionality instead of replacing content in the database. We have the mechanism to find the attachment ID based on the image URL in place (we use it to add the `process:<id>` flag to image URLs;
  - Ensure compatibility with all editing contexts by ensuring editors display the remote image, but we save the proper image URL in the content;

**Comment by HardeepAsrani** [comment]
@abaicus One question is about what we consider new users: someone running offloading/rollback for the first time?

Just curious, will we go with the new flow if the user has used the feature in the past but at the current moment they don't have any images offloaded to Optimole and hence can use the new process?

**Comment by abaicus** [comment]
Yes, but we should ensure no images are offloaded at that point in time (when setting the initial feature flag).
