### ISSUE TITLE
Automatically disable Retina option when Limits are enabled

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/optimole-wp#673]
### What problem does this address?

When I enable Limit Image Dimensions with max width/height, it says in the note that the DPR images will be disabled. However, the option is still enabled in the dashboard.
<img width="1680" alt="image" src="https://github.com/Codeinwp/optimole-wp/assets/86592992/e6bbe9ce-cf10-452e-9d1b-38d791809892">

### What is your proposed solution?

Automatically disable the Retina images option when the Limit Image Dimensions with max width/height is enabled.

### Will this feature require documentation? (Optional)

None

**Comment by abaicus** [comment]
It does disable the underlying functionality.

Maybe we can hide the Retina Setting, or disable the toggle and grey out the setting when the limit is enabled? 

cc @Codeinwp/optimole @Codeinwp/design-team what do you think?

**Comment by AndreeaCristinaRadacina** [comment]
Yes, it works as expected; the only "problem" is with the toggles.

**Comment by mghenciu** [comment]
> cc https://github.com/orgs/Codeinwp/teams/optimole https://github.com/orgs/Codeinwp/teams/design-team what do you think?

**Yes,**  greying out the Retina setting when the limit is enabled - sounds good.

___

We are in working now on improving the Text Descriptions for the features; and noticed that the **Add a new crop image size**, **Smart Cropping** and **Resize large images original source** - have their context a bit blurred in terms of how each works and how those depend on each other or not. Also as the user [mentioned here.](https://github.com/Codeinwp/optimole-wp/issues/621)


Will follow up when we have a final list with the suggested improvements for text.
