### ISSUE TITLE
Add new file types in Exclusions dropdowns

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/optimole-wp#679]
### What problem does this address?

After providing support for different file types, I checked the Exclusions tab, and the dropdowns do not contain all possible extensions.
Right now, it's called Image extension (and "Image" is no longer the only file type), and the extensions contain (SVG, WEBP, PNG, JPG, and GIF) so I cannot exclude my PDF file, for example.
<img width="1508" alt="image" src="https://github.com/Codeinwp/optimole-wp/assets/86592992/a2cf42cf-1540-4f90-abc7-a29c3e764737">

### What is your proposed solution?

Adjust the "Image extension" label to "File extension" or something more suitable, and add the supported extensions in the dropdown.

### Will this feature require documentation? (Optional)

Yes, it required documentation

**Comment by abaicus** [comment]
@AndreeaCristinaRadacina ATM we do no optimizations for file types other than images. That setting only addresses images, so it should be fine as is.

**Comment by AndreeaCristinaRadacina** [comment]
Okay, thank you for checking!
