### ISSUE TITLE
Progress bar look in "Enable Auto Quality powered by ML(Machine Learning)" setting's View Sample

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/optimole-wp#692]
### Description

When clicking on View Sample from the "Enable Auto Quality powered by ML(Machine Learning)" setting, you get a progress bar, which lets you know how much smaller is the image. 
In the case below is 78% smaller, but the progress bar actually shows the 22%.

<img width="1280" alt="Screenshot on 2023-09-27 at 11-45-52" src="https://github.com/Codeinwp/optimole-wp/assets/3266155/53e4cc58-0ef1-4653-b5e1-aa7250f1311c">

If I'm understanding correctly, in the case below, where the progress bar says 90% smaller, the progress bar should be 90% colored, not 10% how it is now.
![Annotation-Annotation on 2023-09-27 at 11-49-53 png](https://github.com/Codeinwp/optimole-wp/assets/3266155/def5feb8-6a2e-4c34-805f-326ffb5da70c)

P.S If I got this wrong, we can ignore it :)

### Step-by-step reproduction instructions

-

### Is the issue you are reporting a regression

No

**Comment by HardeepAsrani** [comment]
Thank you for the report @rodica-andronache, is it also the case when using this branch? https://github.com/Codeinwp/optimole-wp/pull/691

**Comment by rodica-andronache** [comment]
@HardeepAsrani yes, it's the same
