### ISSUE TITLE
Add the option to choose the position of Optimole badge.

### ISSUE THREAD

**Issue by kushh23** [Codeinwp/optimole-wp#693]
### What problem does this address?

A user has inquired about the possibility of changing the position of the Optimole badge that is displayed when the badge option is enabled. Currently, the badge appears on the right side of the website, and the user has expressed concern that it disrupts other important parts of their website's layout.

https://secure.helpscout.net/conversation/2374237989/387218?folderId=2353196
### What is your proposed solution?

To address this issue and provide more flexibility to users, we can implement an option that allows users to choose the position of the Optimole badge. Specifically, adding a new configuration setting in the Optimole settings panel that enables users to select whether they want the badge to be displayed on the left side or the right side of their website.

This solution would provide users with the ability to customize the placement of the badge according to their website's design and layout requirements, ensuring that it does not interfere with other important elements on their pages.

1. Add a new configuration setting in the Optimole settings panel labeled "Badge Position."
2. Provide two options within this setting: "Left" and "Right."
3. By default, set the badge position to "Right" to maintain the current behavior for users who do not wish to change it.
4. When a user selects "Left," dynamically adjust the CSS positioning of the Optimole badge to display it on the left side of the website.

### Will this feature require documentation? (Optional)

None

**Comment by selul** [comment]
@kushh23 this is something that they can do easily with CSS, is not something that we plan to offer in the future. 

Thanks for reporting.
