### ISSUE TITLE
Placeholder color not applied to video

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/optimole-wp#709]
### Description

Even if I toggled on the Lazyload for videos and Iframes, the placeholder color that I previously set is not applied to the video.

### Step-by-step reproduction instructions

1. Go to Settings > Advanced > Lazyload
2. Enable generic placeholder and set a color
3. Enable lazyload for videos and iframes
4. Save changes and check on the frontend

### Screenshots, screen recording, code snippet or Help Scout ticket

<img width="1583" alt="image" src="https://github.com/Codeinwp/optimole-wp/assets/86592992/2fb82b8f-1eb6-4b11-a893-8b9cc6ef5a71">

### Is the issue you are reporting a regression

No

**Comment by abaicus** [comment]
@AndreeaCristinaRadacina videos are lazyloaded differently. They don't use the image placeholder but the loader from the screenshot you attached to the issue. The generic placeholder only applies to images.
