### ISSUE TITLE
Exclude first X images clarifications

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/optimole-wp#712]
Is the _Exclude first X images from the lazyload_ option applied only to PNG images?

I excluded the first 2 images using this option, however, I have a jpg image at the bottom of the page that has also been excluded from lazy loading.

I am not sure if it's expected or if it's a bug.
<img width="1680" alt="image" src="https://github.com/Codeinwp/optimole-wp/assets/86592992/e7df8085-a1fa-4764-a412-5a489c350427">

**Comment by abaicus** [comment]
@AndreeaCristinaRadacina It seems that the image comes from an external source. Could you try replacing it with one sourced from the actual website and let me know if it's still excluded from lazyload?

**Comment by AndreeaCristinaRadacina** [comment]
It's okay now.
So it should be applied no matter the image format, right?

Is there any rule between excluding images from lazy loading from this panel and excluding them from the Exclusions panel, or are they independent?

**Comment by abaicus** [comment]
Yes, it has nothing to do with image format. There is no interdependence between the two ways of excluding images from lazyloading.

**Comment by AndreeaCristinaRadacina** [comment]
Thank you!!

I will close the issue then.
