### ISSUE TITLE
Excluding a page from optimization has effect on the next visited page

### ISSUE THREAD

**Issue by irinelenache** [Codeinwp/optimole-wp#716]
### Description

If i exclude a page from optimization, visit it and then visit a second page, the second one will also be excluded. This will happen even if i refresh the page and is fixed when i visit another non-excluded page. 
Here is a video where the issue is visible https://vertis.d.pr/v/fX0tSa 

### Step-by-step reproduction instructions

1. Have more pages
2. Exclude one page from optimization 
3. Visit the excluded page and then go to a non-excluded page
4. Check if the images on the non-excluded page have Optimole links

### Screenshots, screen recording, code snippet or Help Scout ticket

https://vertis.d.pr/v/fX0tSa

### Environment info

Wordpress 6.3.2 / PHP 7.4 / Optimole 3.10

### Is the issue you are reporting a regression

No

**Comment by selul** [comment]
This was introduced by https://github.com/Codeinwp/optimole-wp/issues/437; I've added a check to target those ajax requests by restricting to POST requests, considering that if those would be GET, it can be targeted directly via the exclusion flags.
