### ISSUE TITLE
Include a Disable All WordPress Generated Image Sizes option

### ISSUE THREAD

**Issue by kushh23** [Codeinwp/optimole-wp#730]
### What problem does this address?

A user has requested a new feature because they are using Optimole for image resizing on their WordPress site. By default, WordPress generates multiple sizes of each uploaded image, which results in an excess of image files. This can lead to bloated media libraries and potentially impact site performance and storage.

However, this behavior is typically unnecessary for users who rely on Optimole, as it optimizes and serves images in the required sizes on the fly. This makes the WordPress-generated sizes unnecessary.

To address this issue, the user is using additional plugins and they feel that Optimole should also handle this option.

1. [Disable Generate Thumbnails](https://wordpress.org/plugins/disable-generate-thumbnails/): This plugin effectively disables WordPress sizes.

2. [Disable Media Sizes](https://wordpress.org/plugins/disable-media-sizes/): While this plugin is useful, it specifically disables WordPress sizes.

 

### What is your proposed solution?

An option enabling users to deactivate all image sizes generated by WordPress. This feature prevents the automatic creation of default image sizes like thumbnail, medium, large, and others when images are uploaded. Additionally, it could include the ability for users to selectively disable image sizes generated specifically by themes and plugins.

### Reference
requested here - https://secure.helpscout.net/conversation/2425099641/393271/
### Will this feature require documentation? (Optional)

None

**Comment by selul** [comment]
I've looked over here and this is not something that we can achieve easily without changing core WP Editor classes. To accommodate this the user can host the images to cloud only.
