### ISSUE TITLE
upgrade box in-plugin

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/optimole-wp#74]
@selul I think we can experiment with showing an upgrade box, like : https://www.dropbox.com/s/78wjsgl8nwy9ppq/Screenshot%202019-01-27%2014.05.36.png?dl=0 .

Upgrade to PRO for Faster CDN, Priority Technical Support, more images & bandwidth. The reasoning is that now it user doesn't check the site he isn't even aware of the PRO version.

Along with that we can of course as we discussed add a notice appearing in Media pages when user limit is at 70% letting him know that we recommend upgrading since he is approaching the limit and performance might decrease.

**Comment by selul** [comment]
managed to add this in 202

**Comment by ineagu** [comment]
@selul I think we should hide this one on laptops, it can create confusion and the dashboard is too small : https://www.dropbox.com/s/erpuhuri71mi293/Screenshot%202019-10-17%2017.48.06.png?dl=0
