### ISSUE TITLE
LazyLoad approach

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/optimole-wp#76]
@selul I think users might want a different lazy-load approach, like 1px approach instead of blurred images. Especially on mobile and low-internet speed, I am not sure the current approach is the best since page weight is bigger, along with phone resources. having this as a sort of advanced option might be interesting, can be for everything or separate for mobile / desktop.

You can see if others are complaining.

**Comment by selul** [comment]
@ineagu yes i thought about this and i have added a FAQ item on how this can be accomplished: https://wordpress.org/plugins/optimole-wp/#can%20i%20remove%20the%20blurry%20placeholder%20from%20the%20lazyload%20effct%20%3F 

Next step would be to have this as a setting, like enable lqip placeholder or so
