### ISSUE TITLE
Images not visible in the editor when they are offloaded and Divi is used

### ISSUE THREAD

**Issue by irinelenache** [Codeinwp/optimole-wp#774]
### Description

If the images are offloaded and Divi theme is used, they won't be visible when i'm trying to edit a page (neither with classic editor or Divi editor). (I saw that the image is visible only when it's added after the Divi editor was opened)
Neve and Divi comparison with offload enabled - https://vertis.d.pr/v/BRIgXL
Divi with offload disabled - https://vertis.d.pr/v/Vk1E3s

Reported here - https://secure.helpscout.net/conversation/2496442699/402515?folderId=2353196

### Step-by-step reproduction instructions

1. Install Divi
2. Create a post/page with images
3. Enable the image offload
4. Go and edit the post/page with images

### Screenshots, screen recording, code snippet or Help Scout ticket

Neve and Divi comparison with offload enabled - https://vertis.d.pr/v/BRIgXL
Divi with offload disabled - https://vertis.d.pr/v/Vk1E3s

Reported here - https://secure.helpscout.net/conversation/2496442699/402515?folderId=2353196

### Environment info

WordPress 6.4.3 / Divi 4.24 / Optimole 3.12.4

### Is the issue you are reporting a regression

No

**Comment by girishpanchal30** [comment]
@irinelenache I tried to reproduce this issue but I can't reproduce this issue. Could you please share your test instance details or reshare the screenshot?

**Comment by kushh23** [comment]
I also tested this and was unable to replicate it with latest version of DIVI
