### ISSUE TITLE
Poorly worded and potentially incorrect warning message

### ISSUE THREAD

**Issue by skilleter** [Codeinwp/optimole-wp#776]
### Description

Warning message:

"It seems your are close to the 5.0000 visits limit with OptiMole for this month."

would read better as:

"It seems you are close to the 5 visits limit with OptiMole for this month. "

i.e. replace 'your' with 'you' and remove the unnecessary 4 zeros after the decimal point.

In any case, 5 visits per month seems a little low when, according to the dashboard, the quota is 1K visits per month.

### Step-by-step reproduction instructions

Install OptiMole. Configure it. See warning message

### Environment info

https://pastebin.com/ufyrfTBA

### Is the issue you are reporting a regression

No

**Comment by skilleter** [comment]
![image](https://github.com/Codeinwp/optimole-wp/assets/5267905/5acf795f-e9f1-4aba-ba21-fab74951831f)

**Comment by abaicus** [comment]
Hello, @skilleter! 

Thank you for reporting this!  

We're going to fix the message wording in the next update.
