### ISSUE TITLE
Fatal error when upgrading to latest version

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/optimole-wp#790]
### Description

On a couple of sites where I had Optimole installed, when I upgraded to the latest version, I got a fatal error. On a third one I didn't get the fatal error. I don't know the setup exactly.

![Screenshot on 2024-04-16 at 14-36-37](https://github.com/Codeinwp/optimole-wp/assets/3266155/fe0fa629-838a-40ba-bc04-e5f10e0fd9db)
![Screenshot on 2024-04-16 at 14-37-05](https://github.com/Codeinwp/optimole-wp/assets/3266155/bc08b59c-0dff-4ab9-b057-db405eaaf142)

### Step-by-step reproduction instructions

I can't provide specific instructions. On 2 out of 3 sites where I had Optimole installed, the fatal error appeared.

### Is the issue you are reporting a regression

Yes, this is a regression.

**Comment by selul** [comment]
Checking.

**Comment by selul** [comment]
Fixed this here https://github.com/Codeinwp/themeisle-sdk/commit/d4545f9bde33c503e7097f724a40565d85ba4865 and released here https://github.com/Codeinwp/optimole-wp/pull/791

Thanks @preda-bogdan and @rodica-andronache for help 🙏
