### ISSUE TITLE
Fatal error with the latest version of plugin

### ISSUE THREAD

**Issue by isaumya** [Codeinwp/optimole-wp#806]
### Description

It seems the latest version of plugin that just been released is throwing a fatal error:

```
PHP Fatal error:  Uncaught InvalidArgumentException: Image width must be "auto" or an integer. in /home/nginx/domains/exaample.com/public/wp-content/plugins/optimole-wp/vendor/codeinwp/optimole-sdk/src/Resource/ImageProperty/WidthProperty.php:31
```

The only solution right now is to downgrade back to the previous version i.e. `3.12.10`

### Step-by-step reproduction instructions

1. Update the plugin
2. Get the PHP fatal error in the logs

### Is the issue you are reporting a regression

Yes, this is a regression.

**Comment by selul** [comment]
Hi @isaumya,

I was not able to replicate this, might be specific to the environment. I've added a potential fix here, please check https://github.com/Codeinwp/optimole-wp/pull/807 and you can install the plugin from here https://verti-artifacts.s3.amazonaws.com/optimole-wp-development-c97cf4c1/optimole-wp.zip

**Comment by selul** [comment]
fixed in the latest version
