### ISSUE TITLE
default lazy images are still loaded from client server

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/optimole-wp#81]
**Describe the bug**

When you visit this page :https://inkmeetspaper.com/product/here-for-you/?attribute_pa_count=single-card as you can see below https://www.dropbox.com/s/ku6p66z84cxopre/Screenshot%202019-03-12%2011.08.21.png?dl=0 there are still images coming from client-server, it seems to be a problem on this part of the code : https://www.dropbox.com/s/8cos4hho4fegdc3/Screenshot%202019-03-12%2011.11.10.png?dl=0

**Comment by selul** [comment]
just a note here, it's related to the json attribute generated by the variation form, which replacer somehow misses. might be due to the htmlentities.
