### ISSUE TITLE
woo sliders behaviour

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/optimole-wp#86]
@selul I am not 100% sure how should sliders in general behave, I guess depends on context, but we can start looking at particular cases, like woo product sliders and see what approach is best since I am not sure if the current one is ideal

E.g: https://inkmeetspaper.com/product/hoppy-birthday/ ( below footer) or product page on shopisle theme: https://www.dropbox.com/s/uszc8rmrmxrnelo/Screenshot%202019-03-26%2012.50.48.png?dl=0 .

Some interesting improvement in my perspective is if we can load the next/prev images in the slider when the slider is in the viewport.

But would be good to gather feedback and see what sort of behaviour is best, since it is not a classic lazyload case.

**Comment by preda-bogdan** [comment]
@GrigoreMihai can we check what are the issues with WooComerce sliders.

Let's make a list and tag it here so we can tackle each issue.

**Comment by GrigoreMihai** [comment]
It already loads the next/prev images only when they are in the viewport 
https://paste.pics/1367e9b9c8ec7cab7540b871ca1ad9d5

**Comment by GrigoreMihai** [comment]
Tested Sliders 

- [ ] Product Slider and Carousel with Category for WooCommerce - **works**
- [ ] Product Slider for WooCommerce - **works**

**Comment by ineagu** [comment]
"It already loads the next/prev images only when they are in the viewport
https://paste.pics/1367e9b9c8ec7cab7540b871ca1ad9d5"

What I meant here was that we can probably for the type of sliders that have high usage ratio to load the full image, not the eco one for +-1 slides when in the viewport, or at least load next/prev image on arrow hover. But this isn't part of the work you are doing now probably :)

**Comment by GrigoreMihai** [comment]
I understand now, thanks for the extra details, yes it isn't right now :)
