### ISSUE TITLE
Images Inside <header> Element Do Not Lazy Load

### ISSUE THREAD

**Issue by kushh23** [Codeinwp/optimole-wp#863]
### Description

A user reported that there is a bug where images placed inside a `<header> `element are not lazy-loaded, and this issue impacts the scaling behavior of other pictures on the page.

1. Images outside the `<header>` element are lazy-loaded and scaled appropriately.
2. Adding an identical image inside the `<header>` element prevents it from being lazy-loaded or scaled.
3. Furthermore, the addition of this image inside the `<header>` causes the previously correctly scaled image outside the `<header> `to stop scaling as well.

I am able to replicate the first two steps easily, but their third point do not exist at my end, on my end, if I use same image then it is lazyloaded outside header element too.

### Step-by-step reproduction instructions

1. Add an image to the Header element. I used the Twenty Twenty theme and added this piece of HTML code to the Header.html File.
![Image](https://github.com/user-attachments/assets/366c85f7-1c11-42dc-bf40-d9132595d726)
2. Change **Bypass Lazy Load for First Images** settings to 0 to ensure that images are lazyloaded.
![Image](https://github.com/user-attachments/assets/924ecb1d-dea7-4978-b941-0df3692c0a74)
3. Check on the site, that this image is not lazyloaded at all.

### Screenshots, screen recording, code snippet or Help Scout ticket

Reported here - https://secure.helpscout.net/conversation/2764612077/441276
Can be checked here - https://verdantfarmer.s1-tastewp.com/test/

![Image](https://github.com/user-attachments/assets/fe48b338-af9f-40db-9aeb-7e9d5e467732)

Images provided by user:

![Image](https://github.com/user-attachments/assets/1fe8d57b-470a-4845-815d-4d8e90668b18)
![Image](https://github.com/user-attachments/assets/9fcea39b-22f4-4262-b1a0-b51ae55e3df5)

### Is the issue you are reporting a regression

No

**Comment by ineagu** [comment]
@selul, this makes sense, but I can see an issue with the fact that we don't do the scaling either, but at the same time, we remove the responsive sizes for those elements.

So if we have a 1000x1000 image in header, it would load at this size, right? Even on mobile.

**Comment by selul** [comment]
@ineagu do you see the sizes being removed on Kush case ?

**Comment by ineagu** [comment]
@selul I haven't seen those sizes there from srcset, but they are not usually added to the logo as far as I can see : 

<img width="1024" height="585" src="https://ionutn.com/wp-content/uploads/2024/01/3c898c94-2146-4d34-bb86-15c247f7216a-1024x585.webp" class="attachment-large size-large wp-post-image" alt="" itemprop="image" decoding="async" fetchpriority="high" srcset="https://ionutn.com/wp-content/uploads/2024/01/3c898c94-2146-4d34-bb86-15c247f7216a-1024x585.webp 1024w, https://ionutn.com/wp-content/uploads/2024/01/3c898c94-2146-4d34-bb86-15c247f7216a-300x171.webp 300w, https://ionutn.com/wp-content/uploads/2024/01/3c898c94-2146-4d34-bb86-15c247f7216a-768x439.webp 768w, https://ionutn.com/wp-content/uploads/2024/01/3c898c94-2146-4d34-bb86-15c247f7216a-1536x878.webp 1536w, https://ionutn.com/wp-content/uploads/2024/01/3c898c94-2146-4d34-bb86-15c247f7216a.webp 1792w" sizes="(max-width: 1024px) 100vw, 1024px">

**Comment by selul** [comment]
@kushh23 I will be closing this since the behaviour is expected to work like this.
