### ISSUE TITLE
Replace fake testimonials :)

### ISSUE THREAD

**Issue by sab2ina** [Codeinwp/optimole-wp#91]
This is along with the lines of our recent discussion on ethics 

We're using our testimonials (Adelina's) to recommend our products, on the Homepage http://prntscr.com/n4l440

Maybe we can replace it with a real customer, same for "sites using Optimole".

**Comment by ineagu** [comment]
is already in works :D

**Comment by ineagu** [comment]
also, the testimonial isn't fake, is just that a better disclosure might help, can be easily seen if you go on vertistudio that sites are owned by the same company, is not hidden tho.

If Chris for e.g in his social media work is using ROP and is enjoying using it, it doesn't mean that he cannot say that ROP is a good product helping him, is just that need to be mentioned that the product is developed by the same company.
